### ISSUE TITLE
Export StatusList for revocation convenience

### ISSUE THREAD

**Issue by kezike** [digitalbazaar/vc-status-list#12]
It would be great if implementers could leverage the utility methods in `StatusList` for revocation purposes. This would prevent the need for each implementer to recreate these methods with the lower-level `bitstring` library. On that note, could we export `StatusList` for use in this npm module? This would look like an extra export line in `main.js` that looks like this: `export { StatusList };`. This would, in turn, be picked up by `index.js` when it imports from `main.js`.

**Comment by dlongley** [comment]
Thanks for the PR! Released in [3.1](https://github.com/digitalbazaar/vc-status-list/commit/afdce5f6f4a00932db0aeb12172985ac64eda527).

**Comment by kezike** [comment]
No problem and thanks for the prompt release @dlongley! Also, for what it's worth, after playing around with this library a bit more, I realized that the `decodeList` function exported from `main.js` returns a fresh instance of `StatusList`, which can then be used to access all instance methods in `StatusList`. This means that we should not really *need* this update, but I suppose it doesn't hurt to keep it.
