### ISSUE TITLE
Add `statusPurpose` to StatusList credential

### ISSUE THREAD

**Issue by Harasz** [digitalbazaar/vc-status-list#14]
Hi team,
I see some incompatibilities between your implementations and StatusList2021 specification.
`credentialsubject` property in StatusList2021Credential should have `statusPurpose`.

Place in your code: https://github.com/digitalbazaar/vc-status-list/blob/8f5341650daf7b7127e3b789bab13ef2bf71d8e5/main.js#L26
Specification: https://w3c-ccg.github.io/vc-status-list-2021/#statuslist2021credential

Maybe it was done on purpose :thinking: If so, let me know the reason.

**Comment by dlongley** [comment]
Seems like a simple oversight to me. Though, I suppose a reason to do it would be information minimization. Only someone with a VC that references the status list credential in a `credentialStatus` section would know the status purpose vs. anyone who stumbled upon the status list credential itself. I'm not sure that that presents some significant privacy benefit, though.

cc: @JSAssassin, @aljones15

**Comment by JSAssassin** [comment]
This has been addressed by https://github.com/digitalbazaar/vc-status-list/pull/15. Closing.
