### ISSUE TITLE
Issues with running `mocha` tests in version `5.0.0`

### ISSUE THREAD

**Issue by kezike** [digitalbazaar/vc-status-list#16]
Sorry, I accidentally and prematurely created this as an empty issue with the title `\`. The issue I am experiencing is that version `5.0.0` of `vc-status-list` seems not to be compatible with `mocha`, whereas an earlier version I was using (`3.0.0`) worked fine with `mocha`. In both versions, the project compiles fine, but the tests fails for the higher version with the following error:
```
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /Users/kayodeezike/Code/projects/digitalcredentials/sign-and-verify-core/src/verifier.spec.ts
```
I have tried at length to debug this issue within the setup of my project and I recognize that this may not be an issue with `vc-status-list`, but since the issue has only surfaced after updating `vc-status-list` I figured I would post here in case it is an issue with this codebase. Let me know if you would like me to provide more information. Thanks in advance!

**Comment by kezike** [comment]
Update: it seems like this issue also does not appear in version `4.0.0`. The main difference I see at first glance is that version 5.0.0 moves the `StatusList.js` and `index.js` into a `lib` folder, where as the earlier versions do not. Since version `4.0.0` has what I need (support for `statusPurpose`), my needs have been met. However, I wonder if it would help to keep this issue open since version `5.0.0` is still problematic with respect to the issue in question. Thoughts?

**Comment by dlongley** [comment]
Closing since the versions have advanced and because it looks like this error was in another project that used this as a dependency; it doesn't look to be an issue with this project itself.
