### ISSUE TITLE
`getCredentialStatus` should take `statusType`

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/vc-status-list#3]
Currently `getCredentialStatus` will just return the first status it finds that matches the `StatusList2021` spec. But a VC could have more than one status. `getCredentialStatus` should have another parameter `statusType` that, for now, supports `revoked` and `suspended` as string values (in the future, it should support any value and the value should be in the status field itself so it can be matched there).

**Comment by aljones15** [comment]
> But a VC could have more than one status.

Just a clarification here WRT to "more than one status":

1. This means a VC's `credentialStatus` property can be a list?
2. This means a VC can have either `RevocationList2021Status ` or `SuspensionList2021Status`?

If case 2 is true, then should we throw if the VC doesn't have a `credentialStatus.type` matching the passed in `statusType`?

**Comment by dlongley** [comment]
1. Yes. This is my read on the spec anyway. I would also think that it would be desirable for a credential to be suspended or revoked -- requiring there to be two possible statuses in a single VC.
2. Yes. Or Both.

Yes, we should throw if the requested `statusType` is not present.

**Comment by aljones15** [comment]
closing as this has been address thanks to @JSAssassin for the reminder.
