### ISSUE TITLE
`_checkStatus` does not check all statuses

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/vc-status-list#4]
Currently `_checkStatus` will just check the first status it finds, but a VC could have more than one status. Instead of calling `getCredentialStatus`, it should iterate through the statuses and check if they are applicable to `StatusList2021` and, if so, check them.

**Comment by aljones15** [comment]
@dlongley need to know how to handle this test case now:

https://github.com/digitalbazaar/vc-status-list/blob/d057c0304772ddad6553c646b62b490e8f59300e/tests/30-main.spec.js#L156-L183

If a status has a type that is not in the `StatusList2021` spec, should we just ignore it?

**Comment by dlongley** [comment]
My understanding is that it should still fail. There's a `statusTypeMatches` helper that would be called from a custom check status function (if more than one status type is supported in a system) that would ensure the type matches before passing to this library's `checkStatus`. Therefore, if that doesn't happen -- and the VC is passed to this library's `checkStatus` function, it should fail, i.e., this library's `checkStatus` *should* make sure the status type is acceptable.

**Comment by dlongley** [comment]
To be more clear on what should happen here -- there should be at least *one* `credentialStatus` that matches. If not -- as here in this test, it should fail.

**Comment by aljones15** [comment]
> To be more clear on what should happen here -- there should be at least _one_ `credentialStatus` that matches. If not -- as here in this test, it should fail.

So if there is one matching and one non-matching ignore the non-matching, but check the matching status?

**Comment by dlongley** [comment]
> So if there is one matching and one non-matching ignore the non-matching, but check the matching status?

Yeah, I think that's the only way we could make it work.

**Comment by aljones15** [comment]
closing as this has been addressed
